# multiple tests suites

language: ruby
rvm:
    - 2.6.0
    
services:
    - postgresql
env:
  global:
    - CC_TEST_REPORTER_ID=6273e941f44274024347e6c2c3153ad5bd3ce4659e8540265466b2069e8fc48b
    - CCTR=./cc-test-reporter
    - TZ=America/Los_Angeles

bundler_args: --without production

before_install:
  - gem install bundler -v 1.17.2
  - bundle update rails

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
  - chmod +x $CCTR
  - $CCTR before-build
  - cp config/database.yml.travis config/databse.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:reset

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

scripts:
  - bundle exec rake db:setup
  - bundle exec rake db:fixtures:load
  - bundle exec rails webpacker:compile
  - bundle exec rspec
  - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json
  - bundle exec cucumber --strict
  - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json

after_script:
  - $CCTR sum-coverage coverage/codeclimate.*.json | $CCTR upload-coverage
  - $CCTR after-build --exit-code $TRAVIS_TEST_RESULT
  - rm -f config/application.yml

notifications:
    - false
